    (function() {
      var O = document.getElementById('secretKeyOverlay'), CB = document.getElementById('secretKeyCloseBtn'), KI = document.getElementById('secretKeyInput'), SB = document.getElementById('secretKeySubmitBtn'), SE = document.getElementById('secretKeyStatus'), IE = document.getElementById('secretKeyInfo'), TB = document.getElementById('secretKeyIconBtn'), PC = document.getElementById('proStatusContainer'), API = 'https://m.mxonlive.xyz/data/191491.php';
      var PU = new Set();
      function DID() { var i = localStorage.getItem('torongo_device_id'); if (!i) { i = 'dev_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9); localStorage.setItem('torongo_device_id', i) } return i }
      function GB() { var u = navigator.userAgent; if (u.includes('Chrome') && !u.includes('Edg')) return 'Chrome'; if (u.includes('Firefox')) return 'Firefox'; if (u.includes('Safari') && !u.includes('Chrome')) return 'Safari'; if (u.includes('Edg')) return 'Edge'; return 'Unknown' }
      function GO() { var u = navigator.userAgent; if (u.includes('Windows')) return 'Windows'; if (u.includes('Mac')) return 'macOS'; if (u.includes('Android')) return 'Android'; if (u.includes('iPhone') || u.includes('iPad')) return 'iOS'; return 'Unknown' }
      async function GIP() { try { var r = await fetch('https://api.ipify.org?format=json'); var d = await r.json(); return d.ip || 'Unknown' } catch (e) { return 'Unknown' } }
      function IA() { return localStorage.getItem('torongo_key_info') !== null }
      async function UU() { var sv = localStorage.getItem('torongo_key_info'); if (sv) { try { var info = JSON.parse(sv), ip = await GIP(), br = GB(), os = GO(); KI.style.display = 'none'; SB.style.display = 'none'; SE.style.display = 'none'; IE.style.display = 'none'; PC.innerHTML = '<div class="pro-device-section"><div class="active-count"><div class="big-num">' + (info.active || 0) + '<span style="font-size:11px;color:#777;"> / ' + (info.max || 1) + '</span></div><div class="big-label">Active Devices</div></div><div class="device-row"><span class="device-label">Browser</span><span class="device-value">' + br + '</span></div><div class="device-row"><span class="device-label">OS</span><span class="device-value">' + os + '</span></div><div class="device-row"><span class="device-label">IP</span><span class="device-value">' + ip + '</span></div><div class="device-row"><span class="device-label">Account Type</span><span class="device-value" style="color:#b0b0b0;">PRO</span></div></div><button class="logout-btn" id="logoutKeyBtn"><i class="fa-solid fa-right-from-bracket"></i> Logout & Deactivate</button>'; setTimeout(function() { var lb = document.getElementById('logoutKeyBtn'); if (lb) lb.addEventListener('click', LO) }, 100) } catch (e) { RU() } } else { RU() } }
      function RU() { KI.style.display = 'block'; SB.style.display = 'block'; SE.style.display = 'block'; IE.style.display = 'block'; PC.innerHTML = ''; }
      function restoreSlider() { if (!window.sideMenuMode) { document.getElementById('compactSlider').classList.remove('hide'); } }
      async function LO() { if (!confirm('Logout & deactivate this device?')) return; var sv = localStorage.getItem('torongo_key_info'); if (!sv) return; try { var info = JSON.parse(sv); await fetch(API, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: info.name, device_id: DID(), action: 'logout' }) }) } catch (e) {} localStorage.removeItem('torongo_key_info'); localStorage.removeItem('torongo_pro_urls'); RU(); if (window.removeProChannels) window.removeProChannels(); O.classList.remove('active'); restoreSlider(); }
      function OP() { O.classList.add('active'); document.getElementById('compactSlider').classList.add('hide'); UU(); if (!IA()) { KI.value = ''; setTimeout(function() { KI.focus() }, 150) } }
      function CL() { O.classList.remove('active'); restoreSlider(); }
      async function VF() { var key = KI.value.trim(); if (!key) { SE.textContent = 'Enter key'; SE.className = 'secret-key-status error'; return } SE.textContent = 'Verifying...'; SE.className = 'secret-key-status'; SB.disabled = true; try { var r = await fetch(API, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ key: key, device_id: DID(), action: 'verify' }) }), d = await r.json(); if (!r.ok || d.error) { SE.textContent = d.error || 'Failed'; SE.className = 'secret-key-status error'; if (d.code === 'LIMIT_REACHED') { IE.textContent = 'Active: ' + d.active + '/' + d.max; IE.className = 'secret-key-info warning' } SB.disabled = false; return } if (d.channels) { d.channels.forEach(function(ch) { PU.add(ch.url) }) } localStorage.setItem('torongo_key_info', JSON.stringify({ name: d.key_name || key, active: d.active_devices, max: d.max_devices })); localStorage.setItem('torongo_pro_urls', JSON.stringify([...PU])); if (window.addProChannels && d.channels) { window.addProChannels(d.channels) } O.classList.remove('active'); restoreSlider(); UU(); } catch (e) { SE.textContent = 'Network error'; SE.className = 'secret-key-status error' } SB.disabled = false }
      window.removeProChannels = function() { var su = localStorage.getItem('torongo_pro_urls'); if (su) { try { PU = new Set(JSON.parse(su)) } catch (e) {} } if (window.filterOutProChannels) window.filterOutProChannels(PU); PU.clear() };
      TB.addEventListener('click', function(e) { e.stopPropagation(); OP() }); CB.addEventListener('click', CL); O.addEventListener('click', function(e) { if (e.target === O) CL() }); SB.addEventListener('click', VF); KI.addEventListener('keydown', function(e) { if (e.key === 'Enter') VF() }); window.openSecretWidget = OP;
    })();
